### ISSUE TITLE
Limit isn't respected with $PREG_SPLIT_DELIM_CAPTURE

### ISSUE THREAD

**Issue by seadoggie01** [genius257/StringRegExpSplit#1]
The code doesn't count the delimiters as part of the limit as seen with this code:
~~`StringRegExpSplit("0,1,2,3,4,5,6,7,8,9", "(\|)", 2, $PREG_SPLIT_DELIM_CAPTURE)`~~
`StringRegExpSplit("0|1|2|3|4|5|6|7|8|9", "(\|)", 2, $PREG_SPLIT_DELIM_CAPTURE)`

Expected: `["0", "|", "1|2|3|4|5|6|7|8|9"]`

Actual: `["0", "|", "1", "|", "2|3|4|5|6|7|8|9"]`

Edit: Forgot to escape pipe in delimiter and used wrong example

**Comment by genius257** [comment]
Hi @seadoggie01 :)

Thank you for taking an interest in my StringRegExpSplit project. :)

Your string within the function call is "0,1,2,3,4,5,6,7,8,9" but should be "0|1|2|3|4|5|6|7|8|9"
I know that it's just a typo when you made the issue and the issue still is relevant.

I will fix it later today, i have prepared more tests to try and prevent this issue won't re-occur in the future.

**Comment by seadoggie01** [comment]
Lol, yup, sure did. I tried changing it after I realized that commas were probably a bad idea since I had to use them to show the array. Forgot to change the top :)

**Comment by genius257** [comment]
Fixed with commit d4e816dbb16a750855b3de33bc93e5df25a3fe60
I will add a [new release](https://github.com/genius257/StringRegExpSplit/releases/tag/1.0.1) immediately.
